### ISSUE TITLE
Examples of create product

### ISSUE THREAD

**Issue by baskettcase** [smalot/magento-client#10]
Do you have an example of how to create a product?

**Comment by smalot** [comment]
Unfortunately I only wrote few sample code
https://github.com/smalot/magento-client/blob/master/docs/catalog/product.md
https://github.com/smalot/magento-client/blob/master/docs/customer/customer.md

**Comment by baskettcase** [comment]
Ok thanks, yeah I've been going through those, so far I've been able to look at the class files and figure out how to get things done. Thanks!
